language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

#Build Environments
os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_e2c4dbf29b26_key -iv $encrypted_e2c4dbf29b26_iv
  -in lab-devops-cloud-314722-843338b0f378.json.enc -out ../lab-devops-cloud-314722-843338b0f378.json
  -d

# Instalação de Módulos que são necessários para a Aplicação.
install:
  - pip install flask

# Defini o script de Teste que deve rodar toda vez que o código for alterado.
script:
  - python -m unittest -v test

deploy:
  - provider: gae
    strategy: api
    api_key: $HEROKU_API_KEY
    edge: true
    app: devopslab-augustogava
    on:
      branch: main
  - provider: gae
    keyfile: ../lab-devops-cloud-314722-843338b0f378.json
    project: lab-devops-cloud-314722
    on:
      branch: main
