# Linguagem Utilizada para Desenvolver a Aplicação
language: python

# Versão que a aplicação suporta.
python:
  - "3.7.9"

os: linux
dist: xenial

before_install:
- openssl aes-256-cbc -K $encrypted_e2c4dbf29b26_key -iv $encrypted_e2c4dbf29b26_iv
  -in lab-devops-cloud-314722-843338b0f378.json.enc -out ../lab-devops-cloud-314722-843338b0f378.json
  -d

jobs:
  include:
    - stage: PROD Deploy
      script: skip
      # Definir o Deploy no Google Cloud
      deploy:
        provider: gae
        keyfile: ../lab-devops-cloud-314722-843338b0f378.json
        project: lab-devops-cloud-314722
        on:
          branch: main

    - stage: PROD TEST
      script:
        - curl https://lab-devops-cloud-314722.uc.r.appspot.com | grep HelloGaby || travis_terminate 1;
